# Generated by Django 6.0.6 on 2026-06-13 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название клиента')),
                ('image', models.ImageField(upload_to='clients/', verbose_name='Логотип клиента')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес офиса')),
                ('main_phone', models.CharField(max_length=30, verbose_name='Основной номер телефона')),
                ('second_phone', models.CharField(max_length=30, verbose_name='Дополнительный номер')),
                ('email', models.EmailField(max_length=254, verbose_name='Адрес электронной почты')),
                ('work_hours', models.CharField(max_length=100, verbose_name='Часы работы')),
                ('map_code', models.TextField(blank=True, help_text='Вствьте iframe или скрипт карты из конструктора карт', null=True, verbose_name='Код интерактивной карты')),
            ],
            options={
                'verbose_name': 'Контакты компании',
                'verbose_name_plural': 'Контакты компании',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=70, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=70, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=70, null=True, verbose_name='Отчество')),
                ('phone_number', models.CharField(max_length=30, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст сообщения')),
                ('privacy', models.BooleanField(verbose_name='Подтверждение на обработку персональных данных')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время отправки')),
            ],
            options={
                'verbose_name': 'Обратная связь клиента',
                'verbose_name_plural': 'Обратная связь',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Заголовок на баннере')),
                ('subtitle', models.TextField(blank=True, max_length=255, null=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='slider', verbose_name='Фоновое изображение')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Поизиция в слайдере')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('link', models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на сайт')),
            ],
            options={
                'verbose_name': 'Слайд на главной',
                'verbose_name_plural': 'Слайды на главной',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название производителя')),
                ('website_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на сайт')),
                ('product_type', models.CharField(choices=[('S', 'ПО'), ('C', 'Железо')], default='S', max_length=1, verbose_name='Тип продукта')),
                ('register', models.BooleanField(default=False, verbose_name='Присутствие в регистре')),
                ('logo', models.ImageField(upload_to='manufacturers/', verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Медиа')),
            ],
            options={
                'verbose_name': 'Медиа',
                'verbose_name_plural': 'Медиа',
            },
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название группы продуктов')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_groups/', verbose_name='Изображение товарной группы')),
            ],
            options={
                'verbose_name': 'Товарная группа',
                'verbose_name_plural': 'Товарные группы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Тип услуги')),
            ],
            options={
                'verbose_name': 'Тип услуги',
                'verbose_name_plural': 'Типы услуг',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Моя компания', max_length=100, verbose_name='Название сайта')),
                ('logo_header', models.ImageField(upload_to='settings/', verbose_name='Логотип')),
                ('copyright_text', models.TextField(default='© 2026 Все права защищены', max_length=255, verbose_name='Текст копирайта')),
                ('seo_title', models.CharField(blank=True, max_length=50, verbose_name='Зоголовок в теге title')),
                ('seo_description', models.TextField(blank=True, verbose_name='Главный SEO Description')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название продукта')),
                ('popularity', models.PositiveIntegerField(default=0, verbose_name='Популярность товара')),
                ('manufacturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.manufacturer', verbose_name='Производитель')),
                ('media', models.ManyToManyField(blank=True, to='core.media', verbose_name='Медиа товара')),
                ('product_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.productgroup', verbose_name='Товарная группа')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['popularity', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название услуги')),
                ('description', models.TextField(verbose_name='Описание услуги')),
                ('popularity', models.PositiveIntegerField(default=0, verbose_name='Популярность услуги')),
                ('service_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.servicetype', verbose_name='Тип услуги')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['popularity', 'name'],
            },
        ),
    ]
