# Generated by Django 6.0.6 on 2026-06-18 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='logo_header',
            field=models.FileField(upload_to='settings/', verbose_name='Логотип'),
        ),
    ]
