# Generated by Django 6.0.6 on 2026-06-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_sitesettings_logo_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='logo',
            field=models.FileField(upload_to='manufacturers/', verbose_name='Логотип'),
        ),
    ]
