# Generated by Django 6.0.6 on 2026-06-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_manufacturer_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='register',
            field=models.BooleanField(default=True, verbose_name='Присутствие в регистре'),
        ),
    ]
