# Generated by Django 6.0.6 on 2026-06-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_manufacturer_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.FileField(upload_to='clients/', verbose_name='Логотип клиента'),
        ),
    ]
