# Generated by Django 6.0.6 on 2026-06-20 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_client_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='media',
        ),
        migrations.RemoveField(
            model_name='product',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_group',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_type',
        ),
        migrations.DeleteModel(
            name='Media',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='ServiceType',
        ),
    ]
