# Generated by Django 6.1.1 on 2026-09-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_product_media_remove_product_manufacturer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='address',
            field=models.CharField(default='г. Сургут Нефтеюганское шоссе, 46', max_length=255, verbose_name='Адрес офиса'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.EmailField(default='a.a.kharchenko@yandex.ru', max_length=254, verbose_name='Адрес электронной почты'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='main_phone',
            field=models.CharField(default='+7 (909) 032 33 22', max_length=30, verbose_name='Основной номер телефона'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='second_phone',
            field=models.CharField(default='+7 (909) 032 33 22', max_length=30, verbose_name='Дополнительный номер'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='work_hours',
            field=models.CharField(default='пн-пт, с 9:00 до 18:00', max_length=100, verbose_name='Часы работы'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo_header',
            field=models.FileField(blank=True, null=True, upload_to='settings/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='seo_title',
            field=models.CharField(blank=True, default='Официальный сайт компании Abis', max_length=50, verbose_name='Зоголовок в теге title'),
        ),
    ]
