# Generated by Django 6.1.1 on 2026-09-22 15:40

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_contacts_address_alter_contacts_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=30, region=None, verbose_name='Номер телефона'),
        ),
    ]
