# Generated by Django 6.1.1 on 2026-09-22 15:48

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_feedback_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='main_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+79090323322', max_length=30, region=None, verbose_name='Основной номер телефона'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='second_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+79090323322', max_length=30, region=None, verbose_name='Дополнительный номер'),
        ),
    ]
