# Generated by Django 6.1.1 on 2026-09-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_contacts_main_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='map_code',
            field=models.TextField(blank=True, help_text='Вствьте src из тега iframe виджета карты', null=True, verbose_name='Код интерактивной карты'),
        ),
    ]
